### PR TITLE
build: Allow skipSphinxTests to work with or without arguments

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
Testing: Run https://web-proxy.openmicroscopy.org/east-ci/job/BIOFORMATS-merge/ with or without validation.

### CODE REVIEW

**Comment by rleigh-codelibre** [comment]
@joshmoore Validation can be enabled now with this option.  Note that it will currently always fail when enabled due to some of the docs links being nonexistet for maven -SNAPSHOT versions.

**Comment by joshmoore** [comment]
Thanks for this, @rleigh-codelibre. For those reading along, the parameter `SKIP_DOCS_VALIDATION` gets used under advanced maven settings as:

```
skipSphinxTests=${SKIP_DOCS_VALIDATION}
```

**Comment by rleigh-codelibre** [comment]
This is also a more specialised form of the general `skipTests` parameter (which can also be used to skip everything, including the sphinx linkchecking).  `skipSphinxTests is specifically for skipping the sphinx linkcheck tests, rather than all tests.

**Comment by joshmoore** [comment]
I've tested this locally from https://github.com/snoopycrimecop/bio-formats-build/tree/east_merge_trigger (using a Dockerfile that I'll describe under https://github.com/ome/bio-formats-test/pull/1). alicona is still failing for me locally, so I'd be inclined to change the default here to `true` though we'll still need a way to pass this value from the top level down to the submodules.

**Comment by rleigh-codelibre** [comment]
@joshmoore The default can be changed, but that means not being in line with the existing maven conventions and options.  It's set appropriately for the documentation build in the job.  We can also create a makefile or other wrapper script which invokes maven with the appropriate options to match ome-documentation.

**Comment by rleigh-codelibre** [comment]
Note: integrated with #3 including a `Makefile` to with separate `html` and `linkcheck` targets, mirroring the existing ome-model docs `Makefile` behaviour.

**Pull request closed without merging**
