### PR TITLE
Update link and owner field for zeiss formats

### PR DESCRIPTION
**Pull request by joshmoore**
Mostly for discussion. In trying to find the list of current supported format vendors, I noticed this:

```
/tmp/bio-formats-documentation-6.1.2-SNAPSHOT/formats $grep Owner: * | cut -f4 -d: | sort | uniq -c
...
   1 //www.zeiss.com/corporate/int/home.html">Carl Zeiss, Inc.</a></p>
   4 //www.zeiss.com/microscopy/int/home.html">Carl Zeiss Microscopy GmbH</a></p>
   1 //www.zeiss.de/corporate/home.html">Zeiss</a></p>
```

### CODE REVIEW

**Comment by joshmoore** [comment]
Disabled oraclejdk8 due to:

Screen Shot 2019-06-25 at 10 44 14

see:
 * https://travis-ci.community/t/install-of-oracle-jdk-8-failing/3038/6
 * https://travis-ci.org/ome/bio-formats-documentation/jobs/549832285

**Comment by joshmoore** [comment]
Now the same thing is happening with oraclejdk11! https://travis-ci.org/ome/bio-formats-documentation/jobs/550170134

**Comment by jburel** [comment]
I removed all oracle testing from omero-install for 5.5

**Comment by joshmoore** [comment]
@dgault @melissalinkert : thoughts?

**Comment by joshmoore** [comment]
If this turns green, I think we're good to go. The only non-`ZEISS International` reference is the specific

```
developer = `Zeiss ...(AxioVision) <https://www.zeiss.com/microscopy/int/products/microscope-software/axiovision.html>`_
```

**Comment by dgault** [comment]
Changes look good and Travis is now happy again

**Pull request merged**
