### PR TITLE
Ignore LOCI hyperlinks.

### PR DESCRIPTION
**Pull request by mtbc**
This PR reduces [BIOFORMATS-linkcheck](https://merge-ci.openmicroscopy.org/jenkins/job/BIOFORMATS-linkcheck/) clutter while LOCI sort out their migration to https://eliceirilab.org/. *Do not merge,* they'll get back to us when they're sorted.

### CODE REVIEW

**Comment by mtbc** [comment]
Could consider just closing this and fixing deeper links with broader pointers to https://eliceirilab.org/.

**Comment by mtbc** [comment]
They'll fix their site "over the next few weeks" then reach out again.

**Comment by sbesson** [comment]
From https://latest-ci.openmicroscopy.org/jenkins/job/BIOFORMATS-linkcheck/39/console it looks like all the deeper link now redirect to https://eliceirilab.org/. 
Shall we close this (as it conflicts with #178 )?

**Comment by mtbc** [comment]
Fine to close this. We should actually update the links to point to within https://eliceirilab.org/ when they finally get themselves together though.

**Pull request closed without merging**
