### PR TITLE
Generate documentation with autogen 

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
- Build autogen source
- Run generation steps
- Remove generated files from git

Testing:

Check all pages are present from the old bioformats docs.  Check the generated summary metadata and formats pages all look sane.

I've imported all the changes up to 5.8.0, so the content should be identical to current bioformats.git modulo some broken model links (because we don't have -SNAPSHOT versions staged).

### CODE REVIEW

**Comment by rleigh-codelibre** [comment]
See https://web-proxy.openmicroscopy.org/east-ci/job/BIOFORMATS-merge/jdk=JDK9,label=testintegration/ws/bio-formats-build/bio-formats-documentation/target/bio-formats-documentation-5.8.0-SNAPSHOT-documentation.zip

**Comment by rleigh-codelibre** [comment]
Java examples are not yet built.  It will need enabling separately.
Not sure why the source files are suffixed, but can be fixed separately as well.

I'll look at the model version not being substituted properly.

**Comment by rleigh-codelibre** [comment]
@sbesson Fixed the model version, and bumped the bioformats version.  Now building 5.8.1-SNAPSHOT pulling from our artifactory.

**Comment by rleigh-codelibre** [comment]
Note: included #4 and added a `Makefile` to with separate `clean`, `html` and `linkcheck` targets, mirroring the existing ome-model docs `Makefile` behaviour.  This can be used as a convenience as in all the other documentation repositories.

**Comment by rleigh-codelibre** [comment]
Green in https://web-proxy.openmicroscopy.org/east-ci/job/BIOFORMATS-merge/31/

**Comment by sbesson** [comment]
Reviewed the output of the last commit and compared it to the content generated by https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-docs/:

- the model version substitution has been fixed
- most of the remaining diff seems to be either difference between release versions and SNAPSHOT or branches on GitHub

Assuming the testing of the example Java classes will be carried out separately, the main remaining concern is the absence of the new formats pages introduced in Bio-Formats 5.8.0:

```
sbesson@ls30630:Downloads $ diff -r html bio-formats-documentation-5.8.1-SNAPSHOT/ | grep "Only in"
Only in html: .doctrees
Only in html/_sources/formats: ionpath-mibi.rst.txt
Only in html/_sources/formats: perkinelmer-vectra-qptiff.rst.txt
Only in html/formats: ionpath-mibi.html
Only in html/formats: perkinelmer-vectra-qptiff.html
```

Once everything has been integrated, it might be interesting to run a final `diff -ru` between the current documentation set and the one generated by this repository in a `latest` build i.e. without the SNAPSHOT bumps.

**Comment by rleigh-codelibre** [comment]
These mibi and vectra formats are showing up in the metadata table and pages, it's the format pages where it's lacking.  Clearly something odd there; is there a static reader list which needs updating or something else affecting the docs generation?

**Comment by sbesson** [comment]
I think 22a1cfa does not include the last set of changes made to `format-pages.txt` - see https://github.com/openmicroscopy/bioformats/commits/v5.8.0/components/autogen/src/format-pages.txt

**Comment by rleigh-codelibre** [comment]
Aha, updated from bioformats develop, and these two formats are now present.

**Comment by rleigh-codelibre** [comment]
Green in https://web-proxy.openmicroscopy.org/east-ci/job/BIOFORMATS-merge/34/ with the missing formats included.

**Comment by rleigh-codelibre** [comment]
By the way, regarding building and testing the example sources, if these went into a separate `bio-formats-examples` component, the docs build could consume the source jar, and the main jar could be made for download as a discrete artefact.

**Comment by joshmoore** [comment]
Merging and capturing the migration of the examples as an issue on this repo. If I've missed any other outstanding issue here, please create a new issue and link.

**Pull request merged**
