### PR TITLE
update uri

### PR DESCRIPTION
**Pull request by jburel**
Point uri to ome_model_doc https://ome-model.readthedocs.io/en/stable/

### CODE REVIEW

**Comment by sbesson** [comment]
Do you foresee the need to override this base URI ever in the near future?
Otherwise, an alternative would be to completely get rid of this variable and its usage in https://github.com/ome/bio-formats-documentation/blob/ab5e213dbf1b5ef9e864ecc2e3a99bc67d83e67c/sphinx/conf.py#L217-L218 and update https://github.com/ome/bio-formats-documentation/blob/ab5e213dbf1b5ef9e864ecc2e3a99bc67d83e67c/sphinx/conf.py#L170 to use the new base URI

**Comment by jburel** [comment]
I think the  BF linkcheck job could use ``latest`` (merge  PR) instead of ``stable`` (release/tag). That will match what was previously in place

**Comment by jburel** [comment]
Discussed during the weekly BF call, we decided not to keep the variable

**Review by dgault — APPROVED** [review]
Changes look good from my side

**Pull request merged**
